use_default_settings: true

general:
  debug: false
  instance_name: "Luphahla Search"
  enable_metrics: true

search:
  safe_search: 1
  autocomplete: "google"
  default_lang: "en"

  formats:
    - html
    - json

  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

  suspended_times:
    SearxEngineAccessDenied: 300
    SearxEngineCaptcha: 1800
    SearxEngineTooManyRequests: 300
    cf_SearxEngineCaptcha: 86400
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 86400

server:
  port: 8080
  bind_address: "0.0.0.0"

  secret_key: "${SEARXNG_SECRET}"

  limiter: false
  public_instance: false
  image_proxy: false

outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
  pool_connections: 20
  pool_maxsize: 10
  enable_http2: true
